### ISSUE TITLE
Not compatible with fish 3.0.0

### ISSUE THREAD

**Issue by rifuso** [chgu82837/theme-PastFish#2]
The prompt file must be changed for this to work with Fish 3.0.0

**Comment by pastleo** [comment]
fix [fish math api changes](https://github.com/fish-shell/fish-shell/blob/master/doc_src/math.txt) at https://github.com/pastleo/theme-PastFish/commit/31de7311f74bf80a21c543f2deb0af3998eb7a26

tested on fish, version 3.0.1
